import { formatDistanceToNow } from "date-fns";
import { Sparkles, AlertTriangle, Info } from "lucide-react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { KpiCard } from "@/components/app/kpi-card";
import { PerformanceChart } from "@/components/app/performance-chart";
import { DateRangeSelect } from "@/components/app/date-range-select";
import { getEmptyOverview, getOverview, getWorkspaceContext } from "@/lib/data";

export const dynamic = "force-dynamic";

const usd = (n: number) =>
  n.toLocaleString("en-US", { style: "currency", currency: "USD" });

// Allowed windows for the overview. The delta always compares against the
// equal-length window just before the selected one.
const RANGES = [
  { value: "7", label: "Last 7 days" },
  { value: "30", label: "Last 30 days" },
  { value: "90", label: "Last 90 days" },
];
const DEFAULT_RANGE = "30";

export default async function DashboardPage({
  searchParams,
}: {
  searchParams: Promise<{ range?: string }>;
}) {
  const { range } = await searchParams;
  const days = RANGES.some((r) => r.value === range)
    ? Number(range)
    : Number(DEFAULT_RANGE);
  const rangeLabel = `Last ${days} days`;

  const { active } = await getWorkspaceContext();
  const data = active ? await getOverview(active.id, days) : getEmptyOverview();

  const syncedLabel = data.lastSyncedAt
    ? `Synced ${formatDistanceToNow(data.lastSyncedAt, { addSuffix: true })}`
    : "Not connected yet";

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">
            {active ? `${active.name} — Overview` : "Overview"}
          </h1>
          <p className="text-sm text-muted-foreground">
            {rangeLabel} · All platforms · {syncedLabel}
          </p>
        </div>
        <DateRangeSelect options={RANGES} defaultValue={DEFAULT_RANGE} />
      </div>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <KpiCard label="Ad Spend" value={usd(data.kpis.spend.value)} deltaPct={data.kpis.spend.deltaPct} comparisonLabel={`previous ${days} days`} invertColors />
        <KpiCard label="Leads" value={String(data.kpis.leads.value)} deltaPct={data.kpis.leads.deltaPct} comparisonLabel={`previous ${days} days`} />
        <KpiCard label="Cost per Lead" value={usd(data.kpis.cpl.value)} deltaPct={data.kpis.cpl.deltaPct} comparisonLabel={`previous ${days} days`} invertColors />
        <KpiCard label="CTR" value={`${data.kpis.ctr.value.toFixed(2)}%`} deltaPct={data.kpis.ctr.deltaPct} comparisonLabel={`previous ${days} days`} />
      </div>

      <div className="grid gap-4 lg:grid-cols-3">
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>Spend & Leads — {rangeLabel.toLowerCase()}</CardTitle>
            <CardDescription>
              Daily performance across all connected platforms
            </CardDescription>
          </CardHeader>
          <CardContent>
            {data.series.length ? (
              <PerformanceChart data={data.series} />
            ) : (
              <p className="flex h-[280px] items-center justify-center text-sm text-muted-foreground">
                No activity in the {rangeLabel.toLowerCase()}.
              </p>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-primary" />
              AI Insights
            </CardTitle>
            <CardDescription>Generated by the analyst engine</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {data.insights.length ? (
              data.insights.map((insight) => (
                <div key={insight.title} className="rounded-lg border p-3">
                  <div className="flex items-start gap-2">
                    {insight.severity === "critical" ? (
                      <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-red-500" />
                    ) : (
                      <Info className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                    )}
                    <p className="text-sm font-medium leading-snug">{insight.title}</p>
                  </div>
                </div>
              ))
            ) : (
              <p className="text-sm text-muted-foreground">
                No insights yet — they are generated automatically once enough
                synced data accumulates.
              </p>
            )}
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Top campaigns</CardTitle>
          <CardDescription>By spend, {rangeLabel.toLowerCase()}</CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {data.topCampaigns.length === 0 && (
            <p className="text-sm text-muted-foreground">
              No campaign activity yet. Connect an ad account in Settings →
              Connections.
            </p>
          )}
          {data.topCampaigns.map((c) => (
            <div key={c.id} className="flex items-center justify-between rounded-lg border p-3">
              <div className="min-w-0">
                <p className="truncate text-sm font-medium">{c.name}</p>
                <p className="text-xs text-muted-foreground">
                  {c.platform === "meta" ? "Meta" : "Google Ads"} · {c.objective ?? "—"}
                </p>
              </div>
              <div className="flex items-center gap-6 text-sm">
                <div className="text-right">
                  <p className="font-medium">{usd(c.spend)}</p>
                  <p className="text-xs text-muted-foreground">spend</p>
                </div>
                <div className="text-right">
                  <p className="font-medium">{c.leads}</p>
                  <p className="text-xs text-muted-foreground">leads</p>
                </div>
                <div className="w-20 text-right">
                  <p className="font-medium">{c.cpl ? usd(c.cpl) : "—"}</p>
                  <p className="text-xs text-muted-foreground">CPL</p>
                </div>
                <Badge variant={c.status === "ACTIVE" ? "default" : "secondary"}>
                  {c.status}
                </Badge>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>
    </div>
  );
}
